# DB ?? ??
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: C##OHGIRAFFERS
    password: OHGIRAFFERS
# JPA ??
  jpa: #spring-jpa?? ? ??!
    generate-ddl: false
    show-sql: true #???? SQL? ??? ??
    database: oracle
    properties:
      hibernate:
        format_sql: true #SQL ??? ??
